AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello_python.my_handler
      Runtime: python3.6
      CodeUri: .

  HelloWorldApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello_python.my_handler
      Runtime: python3.6
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /HelloWorldApiFunction
            Method: any

  SplotrLogMag:
    Type: AWS::Serverless::Function
    Properties:
      Handler: splotr.my_handler
      Runtime: python3.6
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /SplotrLogMag
            Method: any
